type = "javascript"
account_id = "c803c5d87e5620c5617743daaccd921d"
compatibility_date = "2021-11-17"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "npm run build:worker"
upload.format = "service-worker"

[env.dev]
name = "spitter_dev"
workers_dev = true
route = ""
zone_id = ""

[env.prod]
name = "spitter_prod"
route = "spitter.app/*"
zone_id = "9dc3b28e54aeaaf30a1329500fd19f3f"
