name: Deploy Rules PROD

on:
  push:
    branches: [main]
    paths:
      - 'firestore.indexes.json'
      - 'firestore.rules'
      - 'storage.rules'

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only storage,firestore --project spitter-prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
