name: Deploy Frontend DEV

on:
  push:
    branches: [dev]
    paths-ignore:
      - 'backend/**'

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - run: cd frontend/; npm i

      - run: cd frontend/; npm run deploy:worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
