name: Deploy Rules DEV

on:
  push:
    branches: [dev]
    paths:
      - 'firestore.indexes.json'
      - 'firestore.rules'
      - 'storage.rules'

jobs:
  deploy_rules:
    runs-on: ubuntu-latest
    steps:
      - run: ls

      - name: Setup Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only storage,firestore --project spitter-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
